export default {
  IS_LOADING: 'IS_LOADING',
  FETCH_HISTORY_FEED: 'FETCH_HISTORY_FEED',
  SET_HISTORY_FEED: 'SET_HISTORY_FEED',
  FETCH_HISTORY_DETAIL: 'FETCH_HISTORY_DETAIL',
  SET_HISTORY_DETAIL: 'SET_HISTORY_DETAIL',
  FETCH_LAUNCHES: 'FETCH_LAUNCHES',
  SET_LAUNCHES: 'SET_LAUNCHES',
  FETCH_LAUNCH_DETAIL: 'FETCH_LAUNCH_DETAIL',
  SET_LAUNCH_DETAIL: 'SET_LAUNCH_DETAIL',
};
