export default {
  IS_LOADING: 'IS_LOADING',
  FETCH_HISTORY_FEED: 'FETCH_HISTORY_FEED',
  SET_HISTORY_FEED: 'SET_HISTORY_FEED',
  FETCH_HISTORY_DETAIL: 'FETCH_HISTORY_DETAIL',
  SET_HISTORY_DETAIL: 'SET_HISTORY_DETAIL',
};
